const CATALOG = [
  { id: 'audio-fatihah', title: 'تلاوة سورة الفاتحة', kind: "tilawa", duration: '0:44', audio: "audio/surat-al-fatihah.mp3", note: "من مداد" },
  { id: 'audio-naba', title: 'تلاوة سورة النبأ', kind: "tilawa", duration: '4:49', audio: "audio/surat-an-naba.mp3", note: "من مداد" },
  { id: 'audio-infitar', title: 'تلاوة سورة الانفطار', kind: "tilawa", duration: '1:56', audio: "audio/surat-al-infitar.mp3", note: "من مداد" },
  { id: 'audio-mutaffifin', title: 'تلاوة سورة المطففين', kind: "tilawa", duration: '3:42', audio: "audio/surat-al-mutaffifin.mp3", note: "من مداد" },
  { id: 'audio-inshiqaq', title: 'تلاوة سورة الانشقاق', kind: "tilawa", duration: '2:20', audio: "audio/surat-al-inshiqaq.mp3", note: "من مداد" },
  { id: 'audio-buruj', title: 'تلاوة سورة البروج', kind: "tilawa", duration: '2:46', audio: "audio/surat-al-buruj.mp3", note: "من مداد" },
  { id: 'audio-tariq', title: 'تلاوة سورة الطارق', kind: "tilawa", duration: '1:25', audio: "audio/surat-at-tariq.mp3", note: "من مداد" },
  { id: 'audio-ala', title: 'تلاوة سورة الأعلى', kind: "tilawa", duration: '1:27', audio: "audio/surat-al-ala.mp3", note: "من مداد" },
  { id: 'audio-ghashiyah', title: 'تلاوة سورة الغاشية', kind: "tilawa", duration: '2:00', audio: "audio/surat-al-ghashiyah.mp3", note: "من مداد" },
  { id: 'audio-fajr', title: 'تلاوة سورة الفجر', kind: "tilawa", duration: '3:13', audio: "audio/surat-al-fajr.mp3", note: "من مداد" },
  { id: 'audio-balad', title: 'تلاوة سورة البلد', kind: "tilawa", duration: '1:47', audio: "audio/surat-al-balad.mp3", note: "من مداد" },
  { id: 'audio-shams', title: 'تلاوة سورة الشمس', kind: "tilawa", duration: '1:16', audio: "audio/surat-ash-shams.mp3", note: "من مداد" },
  { id: 'audio-layl', title: 'تلاوة سورة الليل', kind: "tilawa", duration: '1:36', audio: "audio/surat-al-layl.mp3", note: "من مداد" },
  { id: 'audio-duha', title: 'تلاوة سورة الضحى', kind: "tilawa", duration: '0:55', audio: "audio/surat-ad-duha.mp3", note: "من مداد" },
  { id: 'audio-zalzalah', title: 'تلاوة سورة الزلزلة', kind: "tilawa", duration: '0:54', audio: "audio/surat-az-zalzalah.mp3", note: "من مداد" },
  { id: 'audio-nas-midad', title: 'تلاوة سورة الناس — مداد', kind: "tilawa", duration: '0:35', audio: "audio/surat-an-nas-midad.mp3", note: "من مداد" },
  { id: 'audio-falaq-midad', title: 'تلاوة سورة الفلق — مداد', kind: "tilawa", duration: '0:26', audio: "audio/surat-al-falaq-midad.mp3", note: "من مداد" },
  { id: 'audio-ikhlas-midad', title: 'تلاوة سورة الإخلاص — مداد', kind: "tilawa", duration: '0:16', audio: "audio/surat-al-ikhlas-midad.mp3", note: "من مداد" },
  { id: 'audio-kafirun-midad', title: 'تلاوة سورة الكافرون — مداد', kind: "tilawa", duration: '0:34', audio: "audio/surat-al-kafirun-midad.mp3", note: "من مداد" },
  { id: 'audio-maun-midad', title: 'تلاوة سورة الماعون — مداد', kind: "tilawa", duration: '0:41', audio: "audio/surat-al-maun-midad.mp3", note: "من مداد" },
  { id: 'audio-quraysh-midad', title: 'تلاوة سورة قريش — مداد', kind: "tilawa", duration: '0:26', audio: "audio/surat-quraysh-midad.mp3", note: "من مداد" },
  { id: 'audio-asr-midad', title: 'تلاوة سورة العصر — مداد', kind: "tilawa", duration: '0:21', audio: "audio/surat-al-asr-midad.mp3", note: "من مداد" },
  { id: 'audio-nas', title: 'تلاوة سورة الناس', kind: "tilawa", duration: '0:32', audio: 'audio/surat-an-nas.mp3', note: "تسجيل صوتي" },
  { id: 'audio-falaq', title: 'تلاوة سورة الفلق', kind: "tilawa", duration: '0:24', audio: 'audio/surat-al-falaq.mp3', note: "تسجيل صوتي" },
  { id: 'audio-ikhlas', title: 'تلاوة سورة الإخلاص', kind: "tilawa", duration: '0:13', audio: 'audio/surat-al-ikhlas.mp3', note: "تسجيل صوتي" },
  { id: 'audio-kafirun', title: 'تلاوة سورة الكافرون', kind: "tilawa", duration: '0:31', audio: 'audio/surat-al-kafirun.mp3', note: "تسجيل صوتي" },
  { id: 'audio-maun', title: 'تلاوة سورة الماعون', kind: "tilawa", duration: '0:38', audio: 'audio/surat-al-maun.mp3', note: "تسجيل صوتي" },
  { id: 'audio-quraysh', title: 'تلاوة سورة قريش', kind: "tilawa", duration: '0:23', audio: 'audio/surat-quraysh.mp3', note: "تسجيل صوتي" },
  { id: 'audio-asr', title: 'تلاوة سورة العصر', kind: "tilawa", duration: '0:18', audio: 'audio/surat-al-asr.mp3', note: "تسجيل صوتي" },
  { id: 'kl_NaM0lOsE', title: 'تلاوة سورة الدخان', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'bCBLhB49l4U', title: 'تلاوة سورة الرحمن', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'qvGZRvNogpg', title: 'تلاوة سورة النبأ', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'GVcjvvfOktQ', title: 'تلاوة لما تيسر من سورة هود', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'XlmQMRa9HMU', title: 'تلاوة سورة الواقعة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'd223bwic874', title: 'تلاوة سورة الزلزلة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'UOnqYiRRRgY', title: 'تلاوة سورة الحديد', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'ILBE3ZydSfI', title: 'تلاوة سورة البروج', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'K2kT2Mv_BxI', title: 'تلاوة سورة الحجر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'zofslbyqFnM', title: 'تلاوة سورة الصافات', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'qHV9Bg4ENOI', title: 'تلاوة سورة لقمان', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'EEO1d26DycY', title: 'تلاوة سورة فاطر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'pCGnjR2ZNoI', title: 'تلاوة من سورة النمل', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'SOUXMK7th4Q', title: 'تلاوة سورة المطففين', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '0355xnH7kw0', title: 'تلاوة سورة الانفطار', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'sVopy7PX74M', title: 'تلاوة سورة الانشقاق', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'Kh8r8NBwBvs', title: 'تلاوة سورة الجمعة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'a824PBprJZg', title: 'تلاوة سورة الحشر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'Q6ngSEiqa2g', title: 'تلاوة سورة المدثر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'c_io4X1v4yw', title: 'تلاوة سورة الليل', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'c50xIwtS_0o', title: 'تلاوة سورة المزمل', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'GSguJi-IUAU', title: 'تلاوة سورة الفتح', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'jOv5y0UXxRg', title: 'تلاوة سورة محمد', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'Yz2nOFJwksg', title: 'تلاوة سورة القمر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '-asBgvsUy8w', title: 'تلاوة سورة الحج', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'PfqEgtmSztc', title: 'تلاوة سورة الكهف', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '-axVrfjNDJ8', title: 'تلاوة سورة الشورى', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'p34FMoS9GVM', title: 'تلاوة سورة الفاتحة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'a7yFHh81a8o', title: 'تلاوة سورة الممتحنة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 're9whwL7Oik', title: 'تلاوة سورة التوبة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'vtTw-ePetJ0', title: 'تلاوة سورة الصف', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '6xq4pao48ow', title: 'تلاوة سورة الحاقة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'MYG7NB9vIaw', title: 'ما تيسر من سورة الأنفال', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'ezc98w6-8NY', title: 'تلاوة سورة الأحزاب', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'Jv1OhL1nbqg', title: 'تلاوة سورة الزخرف', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'tKKzKV4xDr4', title: 'تلاوة سورة سبأ', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'TrLAHhVwj8k', title: 'تلاوة سورة التغابن', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '2Q9SAZeY6nw', title: 'تلاوة سورة إبراهيم', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'N0w7MMZX150', title: 'تلاوة سورة يس', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'JhoUVobUUvc', title: 'تلاوة سورة يونس', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'TBMm4abhFgA', title: 'تلاوة سورة المرسلات', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '0vOU6MD1MXE', title: 'تلاوة سورة المنافقون', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'PIPhoKXmGus', title: 'ما تيسر من سورة النحل', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'r_1vX-3x9lM', title: 'تلاوة من سورة الأعراف', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'i7eDPN5nXFc', title: 'تلاوة سورة الأحقاف', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'bTbRq0GHXvI', title: 'تلاوة سورة العصر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'UGBzKAJi70k', title: 'تلاوة سورة قريش', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'jLGqh1XTAmU', title: 'تلاوة سورة الماعون', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'SyDDosdEmLs', title: 'تلاوة سورة الإخلاص', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'HdRnRuk3H7s', title: 'تلاوة سورة الكافرون', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'M9ywLT8IaJI', title: 'تلاوة سورة البلد', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'MZWYdrLDSvY', title: 'تلاوة سورة الغاشية', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'iqKa79HpG7Y', title: 'تلاوة سورة الشمس', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '6uHl0gwnu6s', title: 'تلاوة سورة ق', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '32DxT1Rd6QQ', title: 'تلاوة سورة الطارق', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'TKavxL36LRM', title: 'تلاوة سورة الفلق', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: '-Mr5ssp1RKw', title: 'تلاوة سورة الناس', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'i2az1OiNt80', title: 'تلاوة سورة النجم', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'VFH3wjA0eb0', title: 'تلاوة سورة الملك', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'upiovsgmfPw', title: 'تلاوة سورة الأعلى', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'ry_-ZQ0NhaI', title: 'تلاوة سورة الضحى', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'UHamXZ4YDoY', title: 'تلاوة سورة القيامة', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'iXikwkI1d6I', title: 'تلاوة سورة الفجر', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'tB9i1hNK9Os', title: 'تلاوة سورة الفرقان', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 't47CORsmCRU', title: 'تلاوة سورة القصص', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'wjprRtFMDVs', title: 'تلاوة سورة المؤمنون', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'DC4ETEd8esY', title: 'تلاوة سورة القلم', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'kE5C26N9nAo', title: 'ما تيسر من سورة النور', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'hu1jFQU-yqo', title: 'ما تيسر من سورة النساء', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'mcUWPuTBktU', title: 'تلاوة سورة فصلت', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'ZkdqEyFaGEQ', title: 'تلاوة سورة العنكبوت', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'aGBUL7ZoGcQ', title: 'تلاوة سورة الروم', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'MrYBiILrKGc', title: 'تلاوة سورة الطور', kind: 'tilawa', lists: ['tilawa'], source: "يوتيوب" },
  { id: 'xMwATKRljuc', title: '١- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'RWGCtKqKcYI', title: '٢- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'mAbpIG2lj-M', title: '٣- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: '-Lwtk33QLsw', title: '٤- تدبر سورة القصص', kind: 'lesson', lists: ['qasas', 'tadabbur'], source: "يوتيوب" },
  { id: 'xTG8dbMZFuQ', title: '٥- تدبر سورة القصص', kind: 'lesson', lists: ['qasas', 'tadabbur'], source: "يوتيوب" },
  { id: 'GB_5B_74ZiM', title: '٦- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'ZHQkFs9tqwQ', title: '٧- تدبر سورة القصص', kind: 'lesson', lists: ['qasas', 'tadabbur'], source: "يوتيوب" },
  { id: 'yhP7NeEJsic', title: '٨- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'tcW2MfTmxVE', title: '٩- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'lqDC4Oxt3eQ', title: '١٠- تدبر سورة القصص', kind: 'lesson', lists: ['qasas'], source: "يوتيوب" },
  { id: 'DImvpGgl5dY', title: '١١- تدبر سورة القصص', kind: 'lesson', lists: ['qasas', 'tadabbur'], source: "يوتيوب" },
  { id: 'SeC1Xv_gSNo', title: 'مشاعرنا مع القرآن', kind: 'lesson', lists: ['clips'], source: "يوتيوب" },
  { id: 'xIthLZZLhes', title: 'أساس علاقتك بالله', kind: 'lesson', lists: ['clips'], source: "يوتيوب" },
  { id: '9oru2PeF1PU', title: 'أنا صاحبك القرآن', kind: 'lesson', lists: ['clips'], source: "يوتيوب" },
  { id: 'thmttcPhFbw', title: 'خطورة المعاصي', kind: 'lesson', lists: ['clips'], source: "يوتيوب" },
  { id: 'Lpmq1uj7tJc', title: 'ماتستخسرش في القرآن', kind: 'lesson', lists: ['clips'], source: "يوتيوب" },
  { id: 'wuGaXVbdo4w', title: 'تدبر سورة الشرح', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'hGXaNDzsH-Y', title: 'تدبر سورة الفجر', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'yjnz2CVDPTY', title: 'تدبر سورة الضحى (١)', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'pere_MELmB4', title: 'تدبر سورة الضحى (٢)', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'p7YKGXYGJ6E', title: 'تدبر سورة الليل', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'Gmt0lQx_q_I', title: 'تدبر سورة البلد', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: '8sEAlW2dYNg', title: 'تدبر سورة الأعلى', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'PO_49RJODT4', title: 'تدبر سورة الطارق', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'xhD_Fcfuly0', title: 'تدبر سورة الغاشية', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'MzJujK58hcs', title: 'تدبر سورة الشمس', kind: 'lesson', lists: ['tadabbur'], source: "يوتيوب" },
  { id: 'E0R4KZPR0zM', title: 'قتل أصحاب الأخدود', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'AZNnQhRHdFA', title: 'إزاي نتدبر القرآن', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'JCSieVUGsK0', title: 'ولم أكن بدعائك رب شقيا', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: '1KJF3Vn0B7Y', title: 'وجاهدهم به جهادا كبيرا', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'pzTpJNnseWY', title: 'إنا سنلقي عليك قولا ثقيلا', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'XGP7MRRIVvU', title: 'وقفات مع آيات الصيام', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'HjNXc17-XI0', title: 'فتاب عليه', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'X2FwovrC6iY', title: 'وليال عشر', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'b3RU-oTZ9Ac', title: 'املك الزمام', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'anwACrHGOhE', title: 'سمعنا وأطعنا', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: '3aZWyFwowkg', title: 'الذين يستمعون القول فيتبعون أحسنه', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'GvmhEE6Ul8A', title: 'ليحق الحق', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'e851OD2C-bA', title: 'مقاصد الأذكار', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: '5w984xbhuZQ', title: 'ليلة القدر', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: '-cwam4cFUfw', title: 'مجلس في رثاء باسل مؤنس', kind: 'lesson', lists: ['lessons'], source: "يوتيوب" },
  { id: 'I8ttP8KFM48', title: '١- وصدق الله ورسوله', kind: 'lesson', lists: ['sadaq'], source: "يوتيوب" },
  { id: 'jeg6NqM0iQE', title: '٢- وصدق الله ورسوله', kind: 'lesson', lists: ['sadaq'], source: "يوتيوب" },
  { id: '-UxSUr0LC1U', title: '٣- وصدق الله ورسوله', kind: 'lesson', lists: ['sadaq'], source: "يوتيوب" },
  { id: "midad-254263", title: 'سورة الفاتحة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254263" },
  { id: "midad-254329", title: 'ما تيسر من سورة البقرة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254329" },
  { id: "midad-254264", title: 'ما تيسر من سورة النساء', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254264" },
  { id: "midad-254330", title: 'ما تيسر من سورة الأعراف', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254330" },
  { id: "midad-254265", title: 'سورة الأنفال', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254265" },
  { id: "midad-254266", title: 'سورة التوبة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254266" },
  { id: "midad-254331", title: 'ما تيسر من سورة التوبة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254331" },
  { id: "midad-254267", title: 'سورة هود', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254267" },
  { id: "midad-254268", title: 'سورة إبراهيم', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254268" },
  { id: "midad-254332", title: 'ما تيسر من سورة إبراهيم', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254332" },
  { id: "midad-254269", title: 'سورة الحجر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254269" },
  { id: "midad-254333", title: 'ما تيسر من سورة النحل', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254333" },
  { id: "midad-254271", title: 'سورة الكهف', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254271" },
  { id: "midad-254272", title: 'سورة طه', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254272" },
  { id: "midad-254273", title: 'سورة الحج', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254273" },
  { id: "midad-254274", title: 'سورة المؤمنون', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254274" },
  { id: "midad-254275", title: 'سورة الفرقان', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254275" },
  { id: "midad-254276", title: 'سورة القصص', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254276" },
  { id: "midad-254277", title: 'سورة العنكبوت', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254277" },
  { id: "midad-254278", title: 'سورة الروم', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254278" },
  { id: "midad-254279", title: 'سورة لقمان', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254279" },
  { id: "midad-254280", title: 'سورة سبأ', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254280" },
  { id: "midad-254281", title: 'سورة فاطر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254281" },
  { id: "midad-254282", title: 'سورة الصافات', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254282" },
  { id: "midad-254283", title: 'سورة الشورى', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254283" },
  { id: "midad-254284", title: 'سورة الزخرف', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254284" },
  { id: "midad-254285", title: 'سورة الدخان', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254285" },
  { id: "midad-254286", title: 'سورة الأحقاف', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254286" },
  { id: "midad-254287", title: 'سورة محمد', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254287" },
  { id: "midad-254288", title: 'سورة ق', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254288" },
  { id: "midad-254289", title: 'سورة الطور', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254289" },
  { id: "midad-254290", title: 'سورة النجم', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254290" },
  { id: "midad-254291", title: 'سورة القمر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254291" },
  { id: "midad-254292", title: 'سورة الرحمن', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254292" },
  { id: "midad-254293", title: 'سورة الواقعة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254293" },
  { id: "midad-254294", title: 'سورة الحديد', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254294" },
  { id: "midad-254295", title: 'سورة الحشر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254295" },
  { id: "midad-254296", title: 'سورة الممتحنة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254296" },
  { id: "midad-254297", title: 'سورة الصف', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254297" },
  { id: "midad-254298", title: 'سورة الجمعة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254298" },
  { id: "midad-254299", title: 'سورة المنافقون', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254299" },
  { id: "midad-254300", title: 'سورة التغابن', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254300" },
  { id: "midad-254301", title: 'سورة الملك', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254301" },
  { id: "midad-254302", title: 'سورة القلم', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254302" },
  { id: "midad-254303", title: 'سورة الحاقة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254303" },
  { id: "midad-254304", title: 'سورة المزمل', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254304" },
  { id: "midad-254305", title: 'سورة المدثر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254305" },
  { id: "midad-254306", title: 'سورة القيامة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254306" },
  { id: "midad-254307", title: 'سورة المرسلات', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254307" },
  { id: "midad-254308", title: 'سورة النبأ', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254308" },
  { id: "midad-254309", title: 'سورة الانفطار', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254309" },
  { id: "midad-254310", title: 'سورة المطففين', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254310" },
  { id: "midad-254311", title: 'سورة الانشقاق', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254311" },
  { id: "midad-254312", title: 'سورة البروج', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254312" },
  { id: "midad-254313", title: 'سورة الطارق', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254313" },
  { id: "midad-254315", title: 'سورة الغاشية', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254315" },
  { id: "midad-254314", title: 'سورة الأعلى', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254314" },
  { id: "midad-254316", title: 'سورة الفجر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254316" },
  { id: "midad-254317", title: 'سورة البلد', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254317" },
  { id: "midad-254318", title: 'سورة الشمس', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254318" },
  { id: "midad-254319", title: 'سورة الليل', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254319" },
  { id: "midad-254320", title: 'سورة الضحى', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254320" },
  { id: "midad-254321", title: 'سورة الزلزلة', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254321" },
  { id: "midad-254322", title: 'سورة العصر', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254322" },
  { id: "midad-254323", title: 'سورة قريش', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254323" },
  { id: "midad-254324", title: 'سورة الماعون', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254324" },
  { id: "midad-254325", title: 'سورة الكافرون', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254325" },
  { id: "midad-254326", title: 'سورة الإخلاص', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254326" },
  { id: "midad-254327", title: 'سورة الفلق', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254327" },
  { id: "midad-254328", title: 'سورة الناس', kind: "tilawa", lists: ["midad"], source: "مداد", external: "https://midad.com/recitation/254328" },
];
const CHANNEL_TILAWA_COUNT = 73;
const FEATURED_ID = "audio-nas";
